### ISSUE TITLE
Core FS improvements

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_sssfs#18]
1) There are several area's that could be executed more efficiently. E.g. in https://github.com/andrewnicols/moodle/blob/ff44d4899654b2691702c485c9a488262d47b48f/files/classes/filestorage/stored_file.php#L948-L964 get_content is called twice.

2) https://github.com/andrewnicols/moodle/blob/ff44d4899654b2691702c485c9a488262d47b48f/files/classes/filestorage/stored_file.php#L642-L644 needs a attribute check. 

3) https://github.com/andrewnicols/moodle/blob/ff44d4899654b2691702c485c9a488262d47b48f/files/classes/filestorage/file_system.php#L721-L731 never uses the default - i'm assuming it should be returned.

4) file_system::mimetype is called directly in some places and thus cant be overridden

5) Similar to mimetype, it would be nice if image metadata was calculated once and then stored. Perhaps there could be a customdata field in mdl_files interpreted according to mimetype.

6) Many file systems will deal directly with the contenthash field - an index would go a long way with speeding up queries involving the FS.

**Comment by kenneth-hendricks** [comment]
Core does some inefficient things, two examples in stored_file:
-generate_image_thumbnail()
-resize_image()

Both call get_contents twice, which for a remote FS is bad. Look for areas such as these and generate a patch to fix them.

**Comment by kenneth-hendricks** [comment]
[Fri Jan 13 05:18:20.387925 2017] [:error] [pid 2338] [client 192.168.124.191:39366] PHP Notice:  Undefined property: stdClass::$mimetype in /var/www/siteroot/files/classes/filestorage/stored_file.php on line 643, referer: http://192.168.126.141/course/modedit.php?add=resource&type=&course=2&section=0&return=0&sr=0

looks the the get_mimetype function in stored_file needs a null check

**Comment by kenneth-hendricks** [comment]
public static function mimetype_from_path($fullpath, $default = 'document/unknown') {
        $type = $default;

        if (file_exists($fullpath) && class_exists('finfo')) {
            // The type is unknown. Attempt to look up the file type now.
            $finfo = new \finfo(FILEINFO_MIME_TYPE);
            return mimeinfo_from_type('type', $finfo->file($fullpath));
        }

        return 'document/unknown';
    }

should return the default

**Comment by kenneth-hendricks** [comment]
Mimetype methods are static - cant be overriden

**Comment by kenneth-hendricks** [comment]
1) There are several area's that could be executed more efficiently. E.g. in https://github.com/andrewnicols/moodle/blob/ff44d4899654b2691702c485c9a488262d47b48f/files/classes/filestorage/stored_file.php#L948-L964 get_content is called twice.

2) https://github.com/andrewnicols/moodle/blob/ff44d4899654b2691702c485c9a488262d47b48f/files/classes/filestorage/stored_file.php#L642-L644 needs a attribute check. 

3)
https://github.com/andrewnicols/moodle/blob/ff44d4899654b2691702c485c9a488262d47b48f/files/classes/filestorage/file_system.php#L721-L731 never uses the default - i'm assuming it should be returned.

4) file_system::mimetype is called directly in some places and thus cant be overridden

5) Similar to mimetype, it would be nice if image metadata was calculated once and then stored. Perhaps there could be a customdata field in mdl_files interpreted according to mimetype.

**Comment by brendanheywood** [comment]
I think we can close this?
